### ISSUE TITLE
[ Feat ] 알파 배포 전 TODO

### ISSUE THREAD

**Issue by jjunyjjuny** [karrotmvp/errand-front#41]
## :hammer: Feature

> feature name

<br/>

## 📑 체크리스트

- [x] form validation, 버튼 활성화/비활성화 
- [x] tooltip 로그인 마다 한 번만 노출 
- [x] 중간 진입시 뒤로가기 처리 
- [x] 이미지 추가 / 로더
- [ ] API 로더
- [ ] 이미지 viewr + slider (상세페이지)
- [x] 동의하기 뒷배경
- [x] 믹스 패널 
- [x] 모달 뜬 상태에서 뒤로가기 (모달 닫기가 동작하도록)
- [ ] Error boundary => 404로 

<br/>

## ⏰ 예상 소요 시간 [단위: MD]

2MD 

<br/>

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항
